-- ISA-L 2.32.1 ships THREE build systems in the tarball: a hand-written
-- Makefile.unx + make.inc, an autotools setup that is NOT shipped generated
-- (no configure, no aclocal.m4, no Makefile.in anywhere in the 536-entry
-- index), and a CMakeLists.txt upstream labels "Experimental" (README.md:87).
-- Makefile.unx is used here because it needs no autoreconf bootstrap and its
-- per-arch switch is a plain make variable.
--
-- make.inc:43-44 derive host_cpu and arch from uname, which on an x86-64 build
-- machine always says x86_64, so the default is always wrong for a cross build.
-- host_cpu is passed from the system's $HOST_ARCH. That one variable is the
-- whole override, and it is sufficient:
--   * make.inc:47-49 `ifeq ($(host_cpu)_$(arch),aarch64_)` then sets arch=aarch64,
--     so -fcf-protection (make.inc:80-83, x86_64-only) is never added and
--     make.inc:111-112 sets AS=$(CC) -D__ASSEMBLY__;
--   * make.inc:129-131 rewrites any host_cpu that is neither aarch64 nor x86_%
--     to base_aliases, so a 32-bit ARM host_cpu builds the portable C sources;
--   * make.inc:185 probes -pthread with $CC. It COMPILES AND LINKS a test
--     program, but never runs it, so it is legal in a cross build - and it
--     succeeds, because -pthread is a compiler flag Bionic accepts (see
--     stage1.md). It is -pthread, not -lpthread, so no Android sysroot lookup
--     happens.
require("isa-l@source")

return recipe({
    build = [[
        cp -r $NESTDIR/source/isa-l/* .
        # host_cpu comes from the system's $HOST_ARCH, never a literal here.
        # lib is the static archive target (make.inc:295-300); install
        # (make.inc:328-342) additionally wants the shared library, isa-l.h
        # (generated by make.inc:308-319 from the same extern_hdrs list the
        # install rule installs) and the igzip CLI.
        make -j1 -f Makefile.unx host_cpu="$HOST_ARCH" prefix="$OUT" install
    ]]
})
