-- cscope ships a genuine generated configure (270.8K, `Generated by GNU
-- Autoconf 2.69 for cscope 15.9` at line 3), so no autoreconf is needed.
-- flex and bison are required because src/Makefile.in regenerates
-- src/fscanner.c from src/fscanner.l and src/egrep.c from src/egrep.y at
-- build time; both must RUN on the build host, so they are native.
require("flex@native")
require("bison@native")
require("cscope@source")

return recipe({
    build = [[
        cp -r $NESTDIR/source/cscope/* .
        ./configure $AUTOCONF_CONFIGURE_FLAGS
        # config.h.in is the real template name, from configure.in:5
        # AC_CONFIG_HEADERS([config.h:config.h.in]); it is the only one in
        # the tree (verified by `find . -name '*.h.in'` -> ./config.h.in).
        touch aclocal.m4 configure config.h.in
        find . -name 'Makefile.in' | xargs touch
        # With no ncurses package in this prefix, configure.in:254-265
        # searches only host paths (/usr/include, /usr/local/include) and
        # finds nothing; src/Makefile.am then links with no $(CURSES_LIBS).
        # Nothing in this prefix provides ncurses, so the build is left to
        # whatever the target sysroot offers, exactly as upstream defaults.
        make -j"$CORES"
        make -j"$CORES" install
    ]]
})