-- cmph is a plain C library (`libcmph`) plus its `cmph` command-line
-- generator, so this is an ordinary TARGET package: nothing here invokes a
-- compiler, intercepts a build, or needs to run on the build host.
--
-- The build-time generator question, answered from the tree rather than
-- assumed: there is NO perl and NO python in this build. src/Makefile.am:2
-- declares `noinst_PROGRAMS = bm_numbers` and :36 builds it, but no
-- Makefile rule invokes it, so it is built and never run. The bdz lookup
-- table that looks like a generated header is a literal C array already in
-- the tree (src/bdz.c:20, `const cmph_uint8 bdz_lookup_table[] =`), not
-- something regenerated at build time. gendocs and scpscript are t2t/doc
-- helpers for the manual, not part of `make`.
require("cmph@source")

return recipe({
    build = [[
        cp -r $NESTDIR/source/cmph/* .
        # The upstream RELEASE tarball ships a complete generated build
        # system: configure (604968 bytes, "Generated by GNU Autoconf 2.69
        # for cmph 2.0.2" at line 3), aclocal.m4, config.h.in and five
        # Makefile.in files. No autoreconf and no bootstrap is needed.
        #
        # --disable-cxxmph: configure.ac:38-53 hard-errors with "cxxmph
        # demands a working c++0x compiler" when AC_COMPILE_STDCXX_0X fails.
        # The C++ binding is optional and nothing here needs it.
        # --disable-benchmarks: configure.ac:56-62 needs the host-only
        # hopscotch_map.h when enabled.
        # --disable-check is the upstream default (configure.ac:67-69: the
        # check-based unit tests are off unless asked for); passed so the
        # recipe does not lean on a default.
        ./configure $AUTOCONF_CONFIGURE_FLAGS \
            --disable-cxxmph \
            --disable-benchmarks \
            --disable-check
        # config.h.in is the template, from configure.ac:5
        # AC_CONFIG_HEADERS([config.h]); it is the only *.h.in in the tree
        # (`find . -name '*.h.in'` returns just this one). Touching it after
        # ./configure suppresses the autoheader re-run that tarball mtimes
        # would otherwise trigger, since we do not carry aclocal-1.17.
        touch aclocal.m4 configure config.h.in
        find . -name 'Makefile.in' | xargs touch
        make -j"$CORES"
        make -j"$CORES" install
    ]]
})