require("strace@source")

return recipe({
    build = [[
        cp -r $NESTDIR/source/strace/* .
        # Autotools, with a GENERATED configure that ships: 597774 bytes and
        # the banner "Generated by GNU Autoconf 2.72 for strace 7.2". That is
        # how a generated configure is distinguished from a hand-written one;
        # the size alone would not be proof, since a truncated download can
        # fake either one.
        #
        # The config template is src/config.h.in (configure.ac:29,
        # AC_CONFIG_HEADERS([src/config.h])). It is NOT at the top level and is
        # NOT spelled config.h.in there -- there is no top-level one, so a
        # guard naming ./config.h.in would be inert and would leave the
        # autoheader re-run live. Single configure, no AC_CONFIG_SUBDIRS.
        #
        # strace is unusual among these packages in carrying real m4/
        # inputs (m4/mpers.m4 defines the st_MPERS macro used at
        # configure.ac:798-799), so they are touched too, before aclocal.m4,
        # which must end up the newest of the autotools inputs.
        touch m4/*.m4 src/config.h.in
        touch aclocal.m4 configure
        find . -name 'Makefile.in' | xargs touch
        #
        # ptrace COMPILES here even though nothing will ever run the result.
        # configure.ac:417-418 checks struct ptrace_peeksiginfo_args and
        # configure.ac:583-585 checks PTRACE_PEEKUSER/PTRACE_POKEUSER, both
        # including <sys/ptrace.h>; the NDK 28.2 sysroot does ship that header,
        # as does <sys/user.h> which src/regs.h:11 includes.
        # configure.ac:421 also checks <asm/ptrace.h> for s390_compat_regs;
        # the NDK has no asm/ at all, so that check simply fails and the
        # s390 compatibility layer is left out. That is a graceful loss of an
        # x86/s390-only feature, not a build error.
        #
        # libunwind is NOT required. It is opt-in behind --with-libunwind
        # (configure --help, "use libunwind to implement stack tracing
        # support"), src/unwind-libunwind.c is the only file that includes
        # <libunwind-ptrace.h>, and USE_LIBUNWIND stays undefined when the
        # flag is not given. Nothing libunwind provides is needed to compile.
        #
        # --enable-mpers defaults to yes (configure.ac:763) and is deliberately
        # left alone. Its probes degrade rather than fail: the compile probe
        # (m4/mpers.m4:109-115) is compile-only, the runtime probe at :117-124
        # passes its cross-compiling action and answers "no", and the
        # mpers.sh check at :125-133 only runs readelf, a host tool. On
        # aarch64 configure.ac:765-787 looks for a separate AArch32 compiler
        # named arm-linux-gnueabi*-gcc, which the NDK does not provide (it
        # names its wrappers armv7a-linux-androideabi*-clang), so the compat
        # personality is simply skipped.
        #
        # Compiles, but cannot be run here: this binary is a target binary and
        # this project never runs one under an emulator. A strace built for
        # aarch64 is inert until someone runs it on a device.
        ./configure $AUTOCONF_CONFIGURE_FLAGS
        make -j"$CORES"
        make -j"$CORES" install
    ]]
})