require("hwloc@source")

return recipe({
    build = [[
        cp -r $NESTDIR/source/hwloc/* .
        # hwloc 2.13.0 ships a generated configure (stamp: "Generated by GNU
        # Autoconf 2.72 for hwloc 2.13.0") alongside configure.ac.
        #
        # There is NO top-level autotools config template. configure.ac has no
        # AC_CONFIG_HEADERS line at all (verified by grep over the whole file),
        # so there is no config.h to regenerate and nothing to guard at top
        # level. The two config.h.in files that DO exist are hwloc's own
        # hand-written templates for its public/private autogen headers, and
        # they are regenerated by config.status under stamp-h1/stamp-h2
        # (Makefile.in:562,574). They are touched below so that chain stays
        # quiet, exactly like the ordinary template in every other package.
        #
        # Static-only, matching the rest of this prefix.
        ./configure $AUTOCONF_CONFIGURE_FLAGS --enable-static --disable-shared --disable-picky
        touch aclocal.m4 configure include/hwloc/autogen/config.h.in include/private/autogen/config.h.in
        find . -name 'Makefile.in' | xargs touch
        # Every optional dependency probe is turned OFF explicitly. On a cross
        # build these probes are link tests against libraries that are not in
        # this prefix, and a probe that half-succeeds would silently change
        # which components get compiled per system:
        #   --disable-cairo     lstopo graphics back-end; cairo is absent here
        #   --disable-libxml2  XML output falls back to hwloc's own minimal
        #                       writer, which is what we want (libxml2 absent)
        #   --disable-libudev   libudev device discovery; udev is not in the
        #                       prefix and Bionic has no libudev at all
        #   --disable-opencl    --disable-cuda  --disable-nvml
        #   --disable-rsmi      --disable-levelzero  --disable-gl
        #                       none of these vendor SDKs are present
        #   --disable-io        umbrella for the discovery back-ends above
        #   --disable-pci       PCI discovery needs libpciaccess, absent
        # None of these are API-level dependent; they are absent everywhere.
        #
        # No test or example program is built: they are all check_PROGRAMS
        # (tests/hwloc/Makefile.am:32, doc/examples/Makefile.am:23), which
        # `make all` does not build, and hwloc never runs a freshly built
        # target binary during the build - lstopo and the hwloc-* utilities are
        # ordinary bin_PROGRAMS (utils/hwloc/Makefile.am:33,
        # utils/lstopo/Makefile.am:19). They are compiled and installed as
        # target binaries, never executed.
        make -j"$CORES"
        make install
    ]]
})