-- ragel is a HOST tool: a state-machine compiler. It reads a `.rl` grammar
-- and emits C or C++ that is then compiled into some *other* package, so
-- ragel itself must run on the build machine running that package's
-- compiler. A ragel in a target prefix could only generate code nobody
-- compiles here. Consumers should require("ragel@native"), which resolves
-- to this file -- the same shape as packages/bison/generic.lua's
-- gperf@native and packages/libnl-3/generic.lua's flex@native.
require("ragel@source")

return recipe({
    build = [[
        cp -r $NESTDIR/source/ragel/* .
        # A generated configure DOES ship: configure is 178474 bytes and
        # configure:3 reads "# Generated by GNU Autoconf 2.69 for ragel 6.10."
        # (verified in the unpacked tree, not inferred from size).
        #
        # The config template is ragel/config.h.in, NOT a top-level
        # config.h.in: configure.ac:26 uses the deprecated singular macro
        # `AC_CONFIG_HEADER(ragel/config.h)`. `find . -name '*.h.in'` returns
        # exactly one file and it is that one. It is a subdirectory template
        # but NOT a sub-configure -- there is no AC_CONFIG_SUBDIRS, so the
        # single top-level configure covers it.
        #
        # No feature flags are needed. configure.ac:30-31 reads
        #   AS_IF([test -r $srcdir/DIST], [. $srcdir/DIST], [build_parsers=yes;
        #          build_manual=yes])
        # and the release tarball ships DIST, which sets
        # `build_parsers=no; build_manual=no;` (DIST:5-6). So BUILD_PARSERS
        # and BUILD_MANUAL are both off, which is what keeps the build from
        # running anything: the rules that would shell out to a PATH `ragel`
        # (ragel/Makefile.am:55-56) and to `kelbt` (:45-49) live inside
        # `if BUILD_PARSERS`, and the fig2dev/pdflatex rules live inside
        # `if BUILD_MANUAL`. The generated parser sources
        # (ragel/rlscan.cpp, ragel/rlparse.cpp, ragel/rlparse.h) ship in
        # the tarball and are compiled as-is.
        ./configure $AUTOCONF_CONFIGURE_FLAGS
        touch aclocal.m4 configure ragel/config.h.in
        find . -name 'Makefile.in' | xargs touch
        # doc/ragel.1 is generated by configure from doc/ragel.1.in
        # (configure.ac:147, rule at doc/Makefile.in:323), so `make install`
        # finds it without fig2dev. Nothing in `make` needs to execute a
        # built program.
        make -j1
        make -j1 install
    ]]
})
