require("uncrustify@source")

return recipe({
    build = [[
        cp -r $NESTDIR/source/uncrustify/* .
        # Upstream is CMake-only: the release ships no configure and no
        # configure.ac, so there is no autotools timestamp guard to write.
        # cmake_minimum_required(VERSION 3.10) (CMakeLists.txt:1), which the
        # system's -DCMAKE_POLICY_VERSION_MINIMUM=3.5 already covers.
        #
        # include(CTest) at CMakeLists.txt:20 turns BUILD_TESTING on by
        # default, and CMakeLists.txt:565-567 then does enable_testing() and
        # add_subdirectory(tests). Those targets are only ever run by ctest,
        # which we never do on a cross build, so the tests are built for
        # nothing. Turning them off keeps the build to the one binary we
        # actually install (add_executable(uncrustify ...) at :542).
        #
        # There is no system dependency at all. The two things the build
        # shells out to are host tools and are found on the build machine's
        # PATH, which our systems deliberately leave pointing at the host:
        # find_package(Python3 REQUIRED) at CMakeLists.txt:28 runs
        # scripts/make_options.py and scripts/make_punctuator_table.py via
        # py_gen (CMakeLists.txt:189-211), and cmake itself runs
        # cmake/GenerateTokenNames.cmake for token_names.h (:169-177). The
        # version header is generated by cmake/GenerateVersionHeader.cmake,
        # which deliberately tolerates make_version.py failing (lines 17-33,
        # "It's normal for make_version.py to fail when building from a
        # tarball") and falls back to the static 0.83.0 set at
        # CMakeLists.txt:139. So a tarball build needs no git and no Python
        # version machinery, which is why there is no -DNoGitVersionString
        # here: the upstream default is the path designed for this case.
        cmake -S . -B build $CMAKE_FLAGS -DBUILD_TESTING=OFF
        cmake --build build --parallel 1
        cmake --install build
    ]]
})