require("universal-ctags@source")

return recipe({
    build = [[
        cp -r $NESTDIR/source/universal-ctags/* .
        # The RELEASE tarball ships a genuine generated configure (649280
        # bytes, `Generated by GNU Autoconf 2.72 for universal-ctags 6.2.1`
        # at line 3) plus aclocal.m4 and Makefile.in, so no autoreconf is
        # needed. The bare v6.2.1 tag snapshot does NOT (no configure at
        # all, only autogen.sh), which is why the release asset is fetched.
        #
        # --disable-external-sort: configure.ac:499-517 runs the BUILD HOST's
        # `sort` binary as a configure-time probe (`sort -u -f -o file`).
        # It would run here, but it makes the configured feature set depend
        # on whatever sort the build host happens to have. Turning it off
        # selects the internal algorithm (EXTERNAL_SORT undefined) and makes
        # the build self-contained.
        #
        # --disable-xml/json/yaml/seccomp/pcre2: each is a pkg-config probe
        # (configure.ac:706-780 for libxml, and the matching blocks for the
        # others). Every system pins PKG_CONFIG_LIBDIR to $PREFIX and the NDK
        # sysroot and empties PKG_CONFIG_PATH, so these auto-disable and cost
        # nothing; they are passed explicitly so the choice is a decision in
        # the recipe rather than an accident of the prefix.
        ./configure $AUTOCONF_CONFIGURE_FLAGS \
            --disable-external-sort \
            --disable-xml \
            --disable-json \
            --disable-yaml \
            --disable-seccomp \
            --disable-pcre2
        # config.h.in is the template (configure.ac:33 AC_CONFIG_HEADERS).
        # man/GNUmakefile.in is NOT caught by `find -name Makefile.in`, and
        # configure.ac:992 configures man/GNUmakefile, so it is named here.
        touch aclocal.m4 configure config.h.in man/GNUmakefile.in
        find . -name 'Makefile.in' | xargs touch
        make -j1
        make -j1 install
    ]]
})