require("elfutils")
require("ltrace@source")

return recipe({
    build = [[
        cp -r $NESTDIR/source/ltrace/* .
        # Autotools, with a generated configure that ships: 443718 bytes and
        # the banner "Generated by GNU Autoconf 2.68 for ltrace 0.7.3".
        # Config template is config.h.in AT THE TOP LEVEL, from
        # configure.ac:27 AC_CONFIG_HEADERS([config.h]) -- verified present.
        # Not src/config.h.in and not config-h.in. Single configure, no
        # AC_CONFIG_SUBDIRS, though it does carry real m4 input in
        # config/m4 (AC_CONFIG_MACRO_DIR, configure.ac:29) and aux scripts in
        # config/autoconf (AC_CONFIG_AUX_DIR, :30), so those are touched
        # before aclocal.m4, which must stay the newest autotools input.
        touch config/m4/*.m4 config.h.in
        touch aclocal.m4 configure
        find . -name 'Makefile.in' | xargs touch
        #
        # libelf is a hard dependency, not optional: configure.ac:64 raises
        # "*** libelf is a required dependency" and configure.ac:83-87 raises
        # "*** libelf.h or gelf.h not found". That is what packages/elfutils
        # provides, so it is required above.
        #
        # --disable-libunwind is load-bearing, and it is the opposite of what
        # you would guess. ltrace defaults this to "maybe"
        # (configure.ac:133), meaning "use libunwind if its headers are
        # visible" -- not "off". The probe at configure.ac:136-138 looks for
        # libunwind.h and libunwind-ptrace.h, and "maybe" flips to yes when
        # EITHER is found (configure.ac:143-145). packages/libunwind installs
        # libunwind.h, so leaving the default would flip this to yes, after
        # which configure.ac:176-178 does
        # AC_CHECK_LIB([unwind-ptrace], [_UPT_create], ...,
        #                [AC_MSG_ERROR([Couldn't find or use libunwind-ptrace.])]).
        # Our libunwind is built without ptrace support, so that check fails
        # and configure aborts. Turning it off states the answer instead of
        # depending on which headers happen to be installed.
        ./configure $AUTOCONF_CONFIGURE_FLAGS --disable-libunwind
        make -j1
        make -j1 install
    ]]
})