require("armadillo@source")

return recipe({
    build = [[
        cp -r $NESTDIR/source/armadillo/* .
        # Upstream ships BOTH a hand-written ./configure and a CMakeLists.txt.
        # The configure script is 403 bytes of plain POSIX shell that checks
        # for cmake 3.10+ and then runs `cmake $@ .` -- it is NOT an autoconf
        # script (no "Generated by GNU Autoconf" banner, and it is far too
        # small to be one), and there is no configure.ac and no config header
        # template anywhere in the tree, so there is no autotools timestamp
        # guard to write. We configure with cmake directly, which is what that
        # wrapper does anyway.
        #
        # BLAS/LAPACK ARE DELIBERATELY NOT REQUESTED, and the reason is a
        # trap worth stating: -DARMA_USE_LAPACK=OFF CANNOT work. The variable
        # is introduced by a plain `set(ARMA_USE_LAPACK false)` at
        # CMakeLists.txt:73 (under the comment "the settings below will be
        # automatically configured by the rest of this script"), which is an
        # ordinary variable that shadows any same-named cache entry created by
        # a -D flag. Passing it would be silently ignored.
        #
        # Armadillo's own default is fine without them: CMakeLists.txt:485-489
        # only emits "*** WARNING: Use of LAPACK is not enabled ... This will
        # materially degrade the available functionality in Armadillo" when
        # ARMA_USE_LAPACK is false. That is a message(STATUS), not an error,
        # and the build completes. Armadillo is a header library with a
        # two-file wrapper (src/wrapper1.cpp + src/wrapper2.cpp,
        # CMakeLists.txt:580), so a consumer wanting LAPACK links their own.
        #
        # Nothing is required from the prefix, and that is deliberate.
        # packages/lapack is present in this tree but its recipe is a recorded
        # BLOCKER (LAPACK 3.12.1 is 2038 Fortran files and no system here
        # exports $FC), so requiring it would be requiring something that
        # cannot build. packages/openblas does build and does bundle an
        # f2c-converted LAPACK, but requiring it would make this package's
        # behaviour depend on the prefix's contents rather than on its own
        # inputs. See stage1.md for the consequence of that choice on the
        # Android systems, which is subtle.
        #
        # BUILD_SHARED_LIBS=OFF gives the static wrapper library this prefix
        # uses everywhere else. C++14 is set by upstream at CMakeLists.txt:52
        # with CMAKE_CXX_STANDARD_REQUIRED at :53, so no dialect flag is
        # needed here.
        cmake -S . -B build $CMAKE_FLAGS -DBUILD_SHARED_LIBS=OFF
        cmake --build build --parallel "$CORES"
        cmake --install build
    ]]
})